apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: data
    user: admin
    password: password
    basicAuth: false
    isDefault: true
    editable: true
    secureJsonData:
      token: "my_super_secret_auth_token"
    jsonData:
      version: Flux
      timeInterval: "5s"
      defaultBucket: "data"
      organization: "admin"
