---
- name: Check if swap.img exist
  ansible.builtin.stat:
    path: "/swap.img"
  register: swap_img

- name: Swapoff swap.img
  ansible.builtin.shell: |
    swapoff -v /swap.img
    sed -i 's~^/swap.img~#/swap.img~g' /etc/fstab
    rm /swap.img
  register: output
  changed_when: output.rc != 0
  when: swap_img.stat.exists